# Generated by Django 5.1.2 on 2024-10-18 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('house', 'House'), ('apartment', 'Apartment'), ('room', 'Room'), ('office', 'Office')], max_length=10, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='property',
            name='property_type',
        ),
        migrations.AddField(
            model_name='property',
            name='property_type',
            field=models.ManyToManyField(to='property.propertytype'),
        ),
    ]
